In [1]:
import numpy as np
import pandas as pd

In [2]:
enem_sp = pd.read_csv("enem_tratado.csv" , encoding="iso-8859-1")

In [3]:
enem_sp.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",22,M,1,parda,1,Santa Izabel do Pará,1,Não respondeu,NaN,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",19,M,1,parda,1,São Bernardo do Campo,2,Pública,35904958.0,...,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
2,"1,90E+11",23,F,1,branco,1,São Paulo,1,Não respondeu,NaN,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim
3,"1,90E+11",18,F,1,branco,1,Belém,2,Pública,35028927.0,...,612.8,espanhol,1.0,120.0,160.0,120.0,80.0,100.0,580.0,Não
4,"1,90E+11",32,M,1,parda,1,Pratápolis,1,Não respondeu,NaN,...,584.1,espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim

In [4]:
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_NASCIMENTO	 == 'Campinas']
enem_campinas.head(10)

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
69,"1,90E+11",18,M,1,branco,1,Campinas,2,Pública,35017632.0,...,508.2,espanhol,1.0,140.0,140.0,120.0,160.0,120.0,680.0,Sim
143,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
148,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,378.6,Inglês,1.0,120.0,120.0,120.0,120.0,140.0,620.0,Sim
286,"1,90E+11",18,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,605.3,Inglês,1.0,140.0,140.0,120.0,120.0,160.0,680.0,Sim
298,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
334,"1,90E+11",21,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,554.3,espanhol,1.0,140.0,120.0,120.0,120.0,100.0,600.0,Sim
367,"1,90E+11",34,M,2,parda,1,Campinas,1,Não respondeu,NaN,...,630.8,Inglês,1.0,100.0,160.0,100.0,120.0,80.0,560.0,Sim
430,"1,90E+11",19,F,1,branco,1,Campinas,2,Pública,35058836.0,...,665.6,Inglês,1.0,160.0,200.0,160.0,180.0,140.0,840.0,Sim
492,"1,90E+11",39,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,469.1,espanhol,1.0,80.0,120.0,120.0,120.0,120.0,560.0,Sim
562,"1,90E+11",18,M,1,branco,1,Campinas,2,Privada,NaN,...,604.8,Inglês,1.0,160.0,120.0,120.0,160.0,140.0,700.0,Sim

In [5]:
enem_campinas.shape

(9077, 28)

In [6]:
np.random.seed(1) # Para dar a mesma resposta (semente)

In [7]:
amos_simples = enem_campinas.sample(frac=0.20) # Pegou 20% do total de forma aleatoria
amos_simples

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
300285,"1,90E+11",22,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,40.5,Inglês,1.0,100.0,120.0,100.0,120.0,100.0,540.0,Sim
140250,"1,90E+11",18,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,540.7,espanhol,1.0,120.0,120.0,80.0,120.0,80.0,520.0,Não
112630,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,449.1,Inglês,1.0,140.0,180.0,160.0,180.0,140.0,800.0,Sim
274838,"1,90E+11",20,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,653.6,Inglês,1.0,160.0,200.0,140.0,160.0,140.0,800.0,Sim
242278,"1,90E+11",43,F,2,branco,1,Campinas,2,Pública,35980122.0,...,383.8,Inglês,1.0,100.0,80.0,120.0,120.0,80.0,500.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221705,"1,90E+11",18,F,1,parda,1,Campinas,2,Privada,NaN,...,458.8,espanhol,1.0,120.0,100.0,140.0,120.0,40.0,520.0,Sim
108022,"1,90E+11",18,M,1,preta,1,Campinas,2,Pública,35925962.0,...,534.9,Inglês,1.0,80.0,120.0,100.0,100.0,0.0,400.0,Sim
3420,"1,90E+11",20,F,2,parda,1,Campinas,1,Não respondeu,NaN,...,578.2,Inglês,1.0,120.0,100.0,100.0,120.0,120.0,560.0,Sim
41066,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,63.5,Inglês,1.0,140.0,120.0,160.0,120.0,140.0,680.0,Sim
152316,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,619.5,Inglês,1.0,160.0,200.0,160.0,160.0,100.0,780.0,Sim

In [8]:
amos_simples = enem_campinas.sample(3000) # Pegar exatamente 3000 de forma aleatoria
amos_simples

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
100100,"1,90E+11",19,F,1,branco,1,Campinas,2,Privada,NaN,...,418.6,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
123114,"1,90E+11",21,M,1,branco,1,Campinas,1,Não respondeu,NaN,...,799.4,Inglês,1.0,160.0,180.0,180.0,200.0,160.0,880.0,Sim
121412,"1,90E+11",24,F,1,preta,1,Campinas,1,Não respondeu,NaN,...,670.3,espanhol,1.0,120.0,120.0,120.0,120.0,140.0,620.0,Sim
239570,"1,90E+11",19,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,688.8,Inglês,1.0,160.0,200.0,180.0,180.0,200.0,920.0,Sim
318164,"1,90E+11",32,M,1,amarela,1,Campinas,1,Não respondeu,NaN,...,877.6,Inglês,1.0,160.0,140.0,140.0,140.0,100.0,680.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32060,"1,90E+11",18,F,1,parda,1,Campinas,2,Pública,35018797.0,...,410.5,Inglês,1.0,140.0,120.0,120.0,120.0,120.0,620.0,Sim
229032,"1,90E+11",18,M,1,preta,1,Campinas,1,Não respondeu,NaN,...,503.2,Inglês,1.0,120.0,40.0,40.0,120.0,0.0,320.0,Sim
30056,"1,90E+11",20,M,1,branco,1,Campinas,1,Não respondeu,NaN,...,785.4,Inglês,1.0,160.0,200.0,200.0,180.0,160.0,900.0,Sim
74559,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,759.6,Inglês,1.0,120.0,200.0,120.0,140.0,140.0,720.0,Sim
153478,"1,90E+11",22,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,772.5,Inglês,1.0,160.0,200.0,200.0,200.0,200.0,960.0,Sim

In [9]:
np.random.seed(2)

In [10]:
amostra = np.random.choice(a=[0,1], size=9077, replace=True, p=[0.8,0.2]) # 80% indice 0 e 20% indice 1

In [11]:
amostra

array([0, 0, 0, ..., 0, 1, 1], shape=(9077,))

In [12]:
len(amostra[amostra==0])

7241

In [13]:
len(amostra[amostra==1])

1836

In [14]:
amos_simples = enem_campinas.loc[amostra == 1]

In [15]:
amos_simples

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
950,"1,90E+11",18,F,1,parda,1,Campinas,2,Pública,35058836.0,...,561.6,Inglês,1.0,140.0,120.0,140.0,120.0,120.0,640.0,Sim
975,"1,90E+11",24,F,1,nao_declarado,1,Campinas,1,Não respondeu,NaN,...,485.1,Inglês,1.0,100.0,100.0,120.0,120.0,80.0,520.0,Sim
2228,"1,90E+11",20,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,402.7,Inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim
2323,"1,90E+11",20,F,1,preta,1,Campinas,1,Não respondeu,NaN,...,598.4,espanhol,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
2838,"1,90E+11",21,F,1,preta,1,Campinas,1,Não respondeu,NaN,...,517.5,espanhol,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331854,"1,90E+11",20,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,721.4,Inglês,1.0,180.0,180.0,180.0,200.0,180.0,920.0,Sim
331888,"1,90E+11",18,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,56.2,Inglês,1.0,80.0,140.0,100.0,100.0,140.0,560.0,Sim
331996,"1,90E+11",21,F,1,preta,1,Campinas,1,Não respondeu,NaN,...,503.6,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Sim
332353,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,416.9,espanhol,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
332361,"1,90E+11",20,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,701.1,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim

Amostragem Sistemática

In [16]:
enem_campinas.shape

(9077, 28)

In [17]:
np.random.seed(3)
inicio = np.random.choice(10,1) # Escolhe um número até dez

In [18]:
amostra2 = np.arange(inicio.item(), 9077, 100) # Pega o número do inicio, total de elementos, pula de 100 em 100
amostra2

array([   8,  108,  208,  308,  408,  508,  608,  708,  808,  908, 1008,
       1108, 1208, 1308, 1408, 1508, 1608, 1708, 1808, 1908, 2008, 2108,
       2208, 2308, 2408, 2508, 2608, 2708, 2808, 2908, 3008, 3108, 3208,
       3308, 3408, 3508, 3608, 3708, 3808, 3908, 4008, 4108, 4208, 4308,
       4408, 4508, 4608, 4708, 4808, 4908, 5008, 5108, 5208, 5308, 5408,
       5508, 5608, 5708, 5808, 5908, 6008, 6108, 6208, 6308, 6408, 6508,
       6608, 6708, 6808, 6908, 7008, 7108, 7208, 7308, 7408, 7508, 7608,
       7708, 7808, 7908, 8008, 8108, 8208, 8308, 8408, 8508, 8608, 8708,
       8808, 8908, 9008])

In [19]:
amos_sistematica = enem_campinas.iloc[amostra2,:] # iloc busca pelo indice da amostra2

In [20]:
amos_sistematica

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
492,"1,90E+11",39,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,469.1,espanhol,1.0,80.0,120.0,120.0,120.0,120.0,560.0,Sim
5493,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,510.7,Inglês,1.0,120.0,120.0,80.0,120.0,80.0,520.0,Sim
9439,"1,90E+11",18,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,424.9,Inglês,1.0,120.0,120.0,80.0,120.0,60.0,500.0,Sim
13286,"1,90E+11",19,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,538.9,Inglês,1.0,140.0,160.0,140.0,120.0,160.0,720.0,Sim
17299,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,653.3,Inglês,1.0,160.0,140.0,140.0,160.0,160.0,760.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314717,"1,90E+11",24,M,1,amarela,1,Campinas,1,Não respondeu,NaN,...,606.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
318310,"1,90E+11",28,M,2,branco,1,Campinas,1,Não respondeu,NaN,...,572.7,espanhol,1.0,120.0,120.0,80.0,80.0,120.0,520.0,Sim
322675,"1,90E+11",24,M,1,branco,1,Campinas,1,Não respondeu,NaN,...,788.1,Inglês,1.0,140.0,180.0,180.0,180.0,180.0,860.0,Sim
326073,"1,90E+11",18,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,39.8,Inglês,1.0,100.0,80.0,40.0,100.0,0.0,320.0,Sim
329840,"1,90E+11",21,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,545.8,Inglês,1.0,120.0,140.0,120.0,100.0,120.0,600.0,Sim

In [21]:
np.random.seed(4)

In [22]:
inicio =  np.random.choice(10,1)
passo = np.random.randint(100,150,1) # Pega um numero entre 100 até 150

In [23]:
inicio

array([7], dtype=int32)

In [24]:
passo

array([105], dtype=int32)

In [25]:
amostra2 = np.arange(inicio.item(), 9077, passo.item()) # do número do inicio, total, pulando com resultado do passo
amostra2

array([   7,  112,  217,  322,  427,  532,  637,  742,  847,  952, 1057,
       1162, 1267, 1372, 1477, 1582, 1687, 1792, 1897, 2002, 2107, 2212,
       2317, 2422, 2527, 2632, 2737, 2842, 2947, 3052, 3157, 3262, 3367,
       3472, 3577, 3682, 3787, 3892, 3997, 4102, 4207, 4312, 4417, 4522,
       4627, 4732, 4837, 4942, 5047, 5152, 5257, 5362, 5467, 5572, 5677,
       5782, 5887, 5992, 6097, 6202, 6307, 6412, 6517, 6622, 6727, 6832,
       6937, 7042, 7147, 7252, 7357, 7462, 7567, 7672, 7777, 7882, 7987,
       8092, 8197, 8302, 8407, 8512, 8617, 8722, 8827, 8932, 9037])

In [26]:
amostra2_camp = enem_campinas.iloc[amostra2,:]

In [27]:
amostra2_camp

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
430,"1,90E+11",19,F,1,branco,1,Campinas,2,Pública,35058836.0,...,665.6,Inglês,1.0,160.0,200.0,160.0,180.0,140.0,840.0,Sim
5640,"1,90E+11",22,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,653.8,Inglês,1.0,160.0,200.0,140.0,160.0,180.0,840.0,Sim
9787,"1,90E+11",18,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,616.7,espanhol,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
13510,"1,90E+11",19,F,1,branco,1,Campinas,2,Privada,35123080.0,...,573.5,Inglês,1.0,140.0,120.0,120.0,120.0,100.0,600.0,Sim
17945,"1,90E+11",22,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,502.1,espanhol,1.0,140.0,40.0,40.0,120.0,40.0,380.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315118,"1,90E+11",42,M,2,branco,1,Campinas,1,Não respondeu,NaN,...,43.0,Inglês,1.0,80.0,100.0,100.0,80.0,60.0,420.0,Sim
319120,"1,90E+11",18,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,623.1,Inglês,1.0,120.0,120.0,120.0,120.0,140.0,620.0,Sim
323221,"1,90E+11",25,M,1,preta,1,Campinas,1,Não respondeu,NaN,...,619.9,espanhol,1.0,160.0,120.0,120.0,120.0,80.0,600.0,Sim
326975,"1,90E+11",19,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,706.5,Inglês,1.0,120.0,120.0,140.0,120.0,140.0,640.0,Sim
331177,"1,90E+11",19,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,690.4,Inglês,1.0,160.0,120.0,120.0,180.0,120.0,700.0,Sim

Amostragem Estratificada

In [28]:
enem_campinas['RACA'].value_counts()

RACA
branco           5406
parda            2276
preta            1062
amarela           170
nao_declarado     144
indigena           19
Name: count, dtype: int64

In [32]:
branca = enem_campinas.loc[enem_campinas.RACA == 'branco'].sample(frac=0.10)
branca.shape

(541, 28)

In [33]:
parda = enem_campinas.loc[enem_campinas.RACA == 'parda'].sample(frac=0.10)
parda.shape

(228, 28)

In [34]:
preta = enem_campinas.loc[enem_campinas.RACA == 'preta'].sample(frac=0.10)
preta.shape

(106, 28)

In [35]:
amarela = enem_campinas.loc[enem_campinas.RACA == 'amarela'].sample(frac=0.10)
amarela.shape

(17, 28)

In [36]:
indigena = enem_campinas.loc[enem_campinas.RACA == 'indigena'].sample(frac=0.10)
indigena.shape

(2, 28)

In [37]:
amos_estra = pd.concat([branca,preta,parda,amarela,indigena])

In [38]:
amos_estra

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
167691,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35112586.0,...,736.8,Inglês,1.0,160.0,160.0,160.0,200.0,200.0,880.0,Sim
325130,"1,90E+11",26,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,527.8,Inglês,1.0,160.0,120.0,140.0,160.0,140.0,720.0,Sim
170503,"1,90E+11",19,F,1,branco,1,Campinas,2,Pública,35026396.0,...,472.1,Inglês,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
66280,"1,90E+11",25,M,1,branco,1,Campinas,1,Não respondeu,NaN,...,669.6,Inglês,1.0,140.0,140.0,140.0,120.0,80.0,620.0,Sim
95518,"1,90E+11",21,M,1,branco,1,Campinas,1,Não respondeu,NaN,...,518.7,Inglês,1.0,120.0,160.0,120.0,120.0,80.0,600.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194634,"1,90E+11",18,F,1,amarela,1,Campinas,2,Pública,35045664.0,...,417.9,Inglês,1.0,160.0,120.0,120.0,120.0,100.0,620.0,Sim
289778,"1,90E+11",18,M,1,amarela,1,Campinas,1,Não respondeu,NaN,...,846.8,Inglês,1.0,160.0,120.0,180.0,180.0,140.0,780.0,Sim
120751,"1,90E+11",21,F,1,amarela,1,Campinas,1,Não respondeu,NaN,...,388.8,Inglês,1.0,100.0,120.0,80.0,100.0,0.0,400.0,Sim
165915,"1,90E+11",22,M,1,indigena,1,Campinas,2,Pública,NaN,...,439.9,espanhol,1.0,100.0,40.0,40.0,100.0,0.0,280.0,Não
30268,"1,90E+11",19,M,1,indigena,1,Campinas,2,Pública,35980158.0,...,763.5,Inglês,1.0,120.0,100.0,120.0,120.0,100.0,560.0,Sim

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_treino, X_teste, y_treuni, amos_estra = train_test_split(enem_campinas.drop('RACA', axis=1), enem_campinas['RACA'], stratify=enem_campinas['RACA'],test_size=0.10)

In [42]:
amos_estra.shape

(908,)

In [43]:
amos_estra.value_counts()

RACA
branco           541
parda            228
preta            106
amarela           17
nao_declarado     14
indigena           2
Name: count, dtype: int64

In [44]:
amos_estra = amos_estra.index

In [45]:
amos_estra

Index([328709, 223195, 183928, 156407, 180779, 139923, 311942, 139963, 230620,
        74643,
       ...
       143571,   1328, 304360,   4461,  17013, 143000, 111755, 204952,  67443,
       230393],
      dtype='int64', length=908)

In [48]:
amos_estra_camp = enem_campinas.loc[amos_estra,:]

In [49]:
amos_estra_camp

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
328709,"1,90E+11",19,F,1,parda,1,Campinas,2,Pública,35901097.0,...,470.5,Inglês,1.0,120.0,120.0,120.0,120.0,0.0,480.0,Sim
223195,"1,90E+11",18,M,1,branco,1,Campinas,1,Não respondeu,NaN,...,671.9,Inglês,1.0,140.0,120.0,120.0,180.0,160.0,720.0,Sim
183928,"1,90E+11",18,M,0,branco,1,Campinas,2,Privada,35112756.0,...,43.4,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
156407,"1,90E+11",21,F,1,branco,1,Campinas,1,Não respondeu,NaN,...,508.9,Inglês,1.0,140.0,180.0,120.0,160.0,120.0,720.0,Sim
180779,"1,90E+11",18,M,1,branco,1,Campinas,2,Privada,35437153.0,...,733.6,espanhol,1.0,120.0,120.0,120.0,160.0,160.0,680.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143000,"1,90E+11",20,F,1,preta,1,Campinas,1,Não respondeu,NaN,...,491.1,espanhol,1.0,120.0,120.0,120.0,120.0,20.0,500.0,Sim
111755,"1,90E+11",18,M,1,branco,1,Campinas,2,Pública,35003402.0,...,566.8,Inglês,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
204952,"1,90E+11",23,M,1,parda,1,Campinas,1,Não respondeu,NaN,...,433.3,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
67443,"1,90E+11",18,F,1,parda,1,Campinas,1,Não respondeu,NaN,...,609.7,Inglês,1.0,140.0,120.0,140.0,160.0,80.0,640.0,Sim
230393,"1,90E+11",33,F,1,preta,1,Campinas,1,Não respondeu,NaN,...,425.3,Inglês,1.0,140.0,120.0,120.0,120.0,80.0,580.0,Sim

Amostragem por conglomerado

In [52]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'Pública']

In [53]:
escolas_publicas.shape

(1464, 28)

In [54]:
amostra = escolas_publicas['CO_ESCOLA'].value_counts()
amostra

CO_ESCOLA
35045937.0    57
35018797.0    51
35018363.0    48
35045949.0    46
35058836.0    41
              ..
35920083.0     1
35112537.0     1
35112896.0     1
35913996.0     1
35980109.0     1
Name: count, Length: 255, dtype: int64

In [55]:
amostra.index

Index([35045937.0, 35018797.0, 35018363.0, 35045949.0, 35058836.0, 35901097.0,
       35047200.0, 35018089.0, 35018879.0, 35980158.0,
       ...
       35018764.0, 35500012.0, 35114601.0, 35049967.0, 35112707.0, 35920083.0,
       35112537.0, 35112896.0, 35913996.0, 35980109.0],
      dtype='float64', name='CO_ESCOLA', length=255)

In [60]:
amostragem = np.random.choice(a=[0, 1], size=255, replace=True, p=[0.85, 0.15])

In [61]:
amostragem

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [62]:
amos_conglomerado = amostra.loc[amostragem == 1]

In [63]:
amos_conglomerado

CO_ESCOLA
35018089.0    23
35018326.0    21
35047120.0    21
35018508.0    12
35045676.0     6
35907352.0     5
35924544.0     5
35018594.0     4
35042626.0     4
35018818.0     4
35920678.0     3
35040873.0     3
35914897.0     3
35045573.0     3
35065626.0     3
35018478.0     3
35020825.0     2
35035981.0     2
35127784.0     2
35139968.0     2
35462822.0     2
35578587.0     2
35907376.0     1
35496376.0     1
35028472.0     1
35909385.0     1
35070233.0     1
35118084.0     1
35290725.0     1
35456494.0     1
35123754.0     1
35018673.0     1
35042523.0     1
35017224.0     1
35028903.0     1
35923655.0     1
35019306.0     1
35910934.0     1
35010868.0     1
35910788.0     1
35017267.0     1
35290683.0     1
35114601.0     1
35112537.0     1
Name: count, dtype: int64

In [64]:
amos_conglomerado.shape

(44,)

In [65]:
amos_conglomerado.index

Index([35018089.0, 35018326.0, 35047120.0, 35018508.0, 35045676.0, 35907352.0,
       35924544.0, 35018594.0, 35042626.0, 35018818.0, 35920678.0, 35040873.0,
       35914897.0, 35045573.0, 35065626.0, 35018478.0, 35020825.0, 35035981.0,
       35127784.0, 35139968.0, 35462822.0, 35578587.0, 35907376.0, 35496376.0,
       35028472.0, 35909385.0, 35070233.0, 35118084.0, 35290725.0, 35456494.0,
       35123754.0, 35018673.0, 35042523.0, 35017224.0, 35028903.0, 35923655.0,
       35019306.0, 35910934.0, 35010868.0, 35910788.0, 35017267.0, 35290683.0,
       35114601.0, 35112537.0],
      dtype='float64', name='CO_ESCOLA')

In [66]:
amos_conglomerado = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin([35018089.0, 35018326.0, 35047120.0, 35018508.0, 35045676.0, 35907352.0,
       35924544.0, 35018594.0, 35042626.0, 35018818.0, 35920678.0, 35040873.0,
       35914897.0, 35045573.0, 35065626.0, 35018478.0, 35020825.0, 35035981.0,
       35127784.0, 35139968.0, 35462822.0, 35578587.0, 35907376.0, 35496376.0,
       35028472.0, 35909385.0, 35070233.0, 35118084.0, 35290725.0, 35456494.0,
       35123754.0, 35018673.0, 35042523.0, 35017224.0, 35028903.0, 35923655.0,
       35019306.0, 35910934.0, 35010868.0, 35910788.0, 35017267.0, 35290683.0,
       35114601.0, 35112537.0])]

In [67]:
amos_conglomerado

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
1313,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35018326.0,...,656.6,espanhol,1.0,100.0,120.0,120.0,100.0,120.0,560.0,Sim
7391,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35920678.0,...,456.3,Inglês,1.0,120.0,120.0,120.0,120.0,180.0,660.0,Sim
13371,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35047120.0,...,448.7,Inglês,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
15739,"1,90E+11",18,F,1,preta,1,Campinas,2,Pública,35020825.0,...,559.7,Inglês,1.0,140.0,120.0,140.0,120.0,80.0,600.0,Sim
16959,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35018089.0,...,494.8,espanhol,1.0,140.0,120.0,160.0,120.0,180.0,720.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315097,"1,90E+11",18,M,1,branco,1,Campinas,2,Pública,35018594.0,...,52.7,Inglês,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Sim
316524,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35045676.0,...,420.8,Inglês,1.0,120.0,120.0,120.0,140.0,80.0,580.0,Sim
319542,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35112537.0,...,63.8,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim
321592,"1,90E+11",18,F,1,branco,1,Campinas,2,Pública,35045676.0,...,401.2,Inglês,1.0,120.0,120.0,120.0,120.0,60.0,540.0,Sim
325515,"1,90E+11",18,F,1,parda,1,Campinas,2,Pública,35018089.0,...,635.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim