**Tratamento de dados

In [106]:
import numpy as np
import pandas as pd

In [107]:
dados = pd.read_csv('microdados_enem_2019_sp.csv', sep=';', encoding='iso-8859-1')

In [108]:
dados.head(6) # Cabeçalho

,NU_INSCRICAO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",3546801,Santa Isabel,35,SP,22,M,1,3,1,...,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",3538204,Pinhalzinho,35,SP,19,M,1,3,1,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",3550308,São Paulo,35,SP,17,F,1,3,1,...,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",3548708,São Bernardo do Campo,35,SP,19,M,1,3,1,...,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",3549409,São Joaquim da Barra,35,SP,37,M,2,1,1,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B
5,"1,90E+11",3515103,Embu-Guaçu,35,SP,17,F,1,3,1,...,4192.0,0,1.0,120.0,120.0,120.0,120.0,80.0,560.0,B

In [109]:
dados.shape # (linhas,colunas)

(813772, 44)

In [110]:
dados.dtypes # Ver os tipos dos dados

NU_INSCRICAO                   str
CO_MUNICIPIO_RESIDENCIA      int64
NO_MUNICIPIO_RESIDENCIA        str
CO_UF_RESIDENCIA             int64
SG_UF_RESIDENCIA               str
NU_IDADE                     int64
TP_SEXO                        str
TP_ESTADO_CIVIL              int64
TP_COR_RACA                  int64
TP_NACIONALIDADE             int64
CO_MUNICIPIO_NASCIMENTO    float64
NO_MUNICIPIO_NASCIMENTO        str
CO_UF_NASCIMENTO           float64
SG_UF_NASCIMENTO               str
TP_ST_CONCLUSAO              int64
TP_ANO_CONCLUIU              int64
TP_ESCOLA                    int64
TP_ENSINO                  float64
IN_TREINEIRO                 int64
CO_ESCOLA                  float64
CO_MUNICIPIO_ESC           float64
NO_MUNICIPIO_ESC               str
CO_UF_ESC                  float64
SG_UF_ESC                      str
TP_DEPENDENCIA_ADM_ESC     float64
TP_LOCALIZACAO_ESC         float64
TP_SIT_FUNC_ESC            float64
TP_PRESENCA_CN               int64
TP_PRESENCA_CH               int64
TP_PRESENCA_LC               int64
TP_PRESENCA_MT               int64
NU_NOTA_CN                 float64
NU_NOTA_CH                 float64
NU_NOTA_LC                 float64
NU_NOTA_MT                 float64
TP_LINGUA                    int64
TP_STATUS_REDACAO          float64
NU_NOTA_COMP1              float64
NU_NOTA_COMP2              float64
NU_NOTA_COMP3              float64
NU_NOTA_COMP4              float64
NU_NOTA_COMP5              float64
NU_NOTA_REDACAO            float64
Q025                           str
dtype: object

In [111]:
dados1 = dados.drop(columns=['CO_MUNICIPIO_RESIDENCIA'])
dados1.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",Santa Isabel,35,SP,22,M,1,3,1,1506500.0,...,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,35,SP,19,M,1,3,1,1503804.0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,35,SP,17,F,1,3,1,1501402.0,...,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,35,SP,19,M,1,3,1,3548708.0,...,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,35,SP,37,M,2,1,1,3549409.0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [112]:
dados1 = dados1.drop(columns=['CO_UF_RESIDENCIA', 'SG_UF_RESIDENCIA', 'CO_MUNICIPIO_NASCIMENTO'])
dados1.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",Santa Isabel,22,M,1,3,1,Santa Izabel do Pará,15.0,PA,...,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,Jacundá,15.0,PA,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,Belém,15.0,PA,...,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,São Bernardo do Campo,35.0,SP,...,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,São Joaquim da Barra,35.0,SP,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [113]:
dados1 = dados1.drop(columns=['NO_MUNICIPIO_RESIDENCIA', 'CO_UF_NASCIMENTO','SG_UF_NASCIMENTO', 'TP_ANO_CONCLUIU', 'TP_ENSINO', 'CO_MUNICIPIO_ESC' 
                                ,'CO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC'],)
dados1.head()

,NU_INSCRICAO,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,TP_ESCOLA,IN_TREINEIRO,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",22,M,1,3,1,Santa Izabel do Pará,1,1,0,...,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",19,M,1,3,1,Jacundá,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",17,F,1,3,1,Belém,2,3,0,...,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",19,M,1,3,1,São Bernardo do Campo,2,2,0,...,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",37,M,2,1,1,São Joaquim da Barra,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [114]:
dados1 = dados1.drop(columns=['TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC'],)
dados1.head()

,NU_INSCRICAO,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,TP_ESCOLA,IN_TREINEIRO,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",22,M,1,3,1,Santa Izabel do Pará,1,1,0,...,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",19,M,1,3,1,Jacundá,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",17,F,1,3,1,Belém,2,3,0,...,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",19,M,1,3,1,São Bernardo do Campo,2,2,0,...,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",37,M,2,1,1,São Joaquim da Barra,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [115]:
dados1.loc[:, 'NU_NOTA_CN'] /= 10

In [116]:
dados1.head()

,NU_INSCRICAO,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,TP_ESCOLA,IN_TREINEIRO,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",22,M,1,3,1,Santa Izabel do Pará,1,1,0,...,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",19,M,1,3,1,Jacundá,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",17,F,1,3,1,Belém,2,3,0,...,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",19,M,1,3,1,São Bernardo do Campo,2,2,0,...,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",37,M,2,1,1,São Joaquim da Barra,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [117]:
dados1.loc[:, 'NU_NOTA_CH'] /= 10
dados1.loc[:, 'NU_NOTA_MT'] /= 10
dados1.loc[:, 'NU_NOTA_LC'] /= 10

In [118]:
dados1.head()

,NU_INSCRICAO,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,TP_ESCOLA,IN_TREINEIRO,...,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",22,M,1,3,1,Santa Izabel do Pará,1,1,0,...,600.2,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",19,M,1,3,1,Jacundá,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",17,F,1,3,1,Belém,2,3,0,...,731.8,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",19,M,1,3,1,São Bernardo do Campo,2,2,0,...,393.2,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",37,M,2,1,1,São Joaquim da Barra,1,1,0,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [119]:
dados1 = dados1.rename(columns={'NU_NOTA_REDACAO': 'NOTA_REDACAO'})

In [120]:
dados1 = dados1.rename(columns={'NU_NOTA_CN': 'NOTA_CN', 'NU_NOTA_MT': 'NOTA_MT', 'NU_NOTA_CH': 'NOTA_CH',
                        'NU_NOTA_LC': 'NOTA_LC'})

In [121]:
dados1 = dados1.rename(columns={'NU_IDADE': 'IDADE', 'TP_SEXO': 'SEXO', 'TP_COR_RACA': 'RACA', 'Q025': 'INTERNET', 'TP_ESCOLA': 'ESCOLA'
                        ,'NU_NOTA_COMP1': 'COMP1','NU_NOTA_COMP2': 'COMP2','NU_NOTA_COMP3': 'COMP3','NU_NOTA_COMP4': 'COMP4','NU_NOTA_COMP5': 'COMP5' })

In [122]:
dados1['RACA'] = dados1['RACA'].replace({0: 'nao_declarado', 1: 'branco', 2: 'preta', 3: 'parda', 4: 'amarela', 5: 'indigena'})

In [123]:
dados1['TP_LINGUA'] = dados1['TP_LINGUA'].replace([0,1], ['Inglês', 'espanhol'])

In [124]:
dados1.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",22,M,1,parda,1,Santa Izabel do Pará,1,1,0,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",19,M,1,parda,1,Jacundá,1,1,0,...,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",17,F,1,parda,1,Belém,2,3,0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",19,M,1,parda,1,São Bernardo do Campo,2,2,0,...,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",37,M,2,branco,1,São Joaquim da Barra,1,1,0,...,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [125]:
dados1['ESCOLA'] = dados1['ESCOLA'].replace([1,2,3,4], ['Não respondeu', 'Pública', 'Privada', 'Exterior'])
dados1['INTERNET'] = dados1['INTERNET'].replace({'A': 'Não', 'B': 'Sim'})

In [126]:
dados1['IDADE'].value_counts()

IDADE
17    219313
18    147548
19     81236
16     59316
20     53009
       ...
91         1
3          1
4          1
86         1
2          1
Name: count, Length: 80, dtype: int64

In [127]:
dados1['IDADE'].value_counts().sort_index()

IDADE
2     1
3     1
4     1
5     2
6     2
     ..
80    2
81    3
82    2
86    1
91    1
Name: count, Length: 80, dtype: int64

In [149]:
menores_12 = dados1.query('IDADE <= 12')['NO_MUNICIPIO_NASCIMENTO'].value_counts()
print(menores_12)

NO_MUNICIPIO_NASCIMENTO
São Paulo                  4
Tambaú                     1
Dracena                    1
Ribeirão Preto             1
Tanabi                     1
Sertãozinho                1
Santo André                1
Luiziânia                  1
Marília                    1
Angatuba                   1
Vargem Grande Paulista     1
Bilac                      1
Nossa Senhora da Glória    1
Louveira                   1
Assis                      1
Araçatuba                  1
Campinas                   1
Name: count, dtype: int64

In [129]:
dados_maiores_idade = dados1.loc[dados1.IDADE > 17]
dados_maiores_idade.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",22,M,1,parda,1,Santa Izabel do Pará,1,Não respondeu,0,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",19,M,1,parda,1,Jacundá,1,Não respondeu,0,...,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não
3,"1,90E+11",19,M,1,parda,1,São Bernardo do Campo,2,Pública,0,...,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
4,"1,90E+11",37,M,2,branco,1,São Joaquim da Barra,1,Não respondeu,0,...,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
6,"1,90E+11",28,F,1,branco,1,Manaus,1,Não respondeu,0,...,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não

In [130]:
dados_maiores_idade['IDADE'].value_counts().sort_index()

IDADE
18    147548
19     81236
20     53009
21     37242
22     29489
       ...
80         2
81         3
82         2
86         1
91         1
Name: count, Length: 67, dtype: int64

In [131]:
dados_maiores_idade.query('IN_TREINEIRO == 1')['IN_TREINEIRO'].value_counts()

IN_TREINEIRO
1    2697
Name: count, dtype: int64

In [132]:
treineiros = dados_maiores_idade.loc[dados_maiores_idade.IN_TREINEIRO == 1]

In [133]:
treineiros.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
237,"1,90E+11",18,F,1,preta,1,Itaporanga,3,Não respondeu,1,...,470.6,Inglês,1.0,120.0,120.0,120.0,140.0,80.0,580.0,Não
337,"1,90E+11",19,M,0,branco,1,Itabaiana,3,Não respondeu,1,...,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
500,"1,90E+11",31,M,1,preta,1,São Paulo,3,Não respondeu,1,...,581.7,Inglês,1.0,120.0,160.0,140.0,140.0,100.0,660.0,Sim
1128,"1,90E+11",18,M,1,branco,1,Atibaia,3,Não respondeu,1,...,637.7,espanhol,1.0,120.0,180.0,160.0,160.0,200.0,820.0,Sim
1205,"1,90E+11",18,F,1,branco,1,Itapecerica da Serra,3,Não respondeu,1,...,487.7,Inglês,1.0,120.0,160.0,120.0,100.0,100.0,600.0,Sim

In [134]:
vestibulando = dados_maiores_idade.loc[dados_maiores_idade.IN_TREINEIRO == 0]

In [135]:
vestibulando.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",22,M,1,parda,1,Santa Izabel do Pará,1,Não respondeu,0,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",19,M,1,parda,1,Jacundá,1,Não respondeu,0,...,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não
3,"1,90E+11",19,M,1,parda,1,São Bernardo do Campo,2,Pública,0,...,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
4,"1,90E+11",37,M,2,branco,1,São Joaquim da Barra,1,Não respondeu,0,...,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
6,"1,90E+11",28,F,1,branco,1,Manaus,1,Não respondeu,0,...,NaN,Inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não

In [136]:
vestibulando.shape

(520457, 29)

In [137]:
dados1.query('IN_TREINEIRO == 0')['IN_TREINEIRO'].value_counts()

IN_TREINEIRO
0    719781
Name: count, dtype: int64

In [138]:
dados1.query('NOTA_REDACAO >= 900.0')['NOTA_REDACAO'].value_counts().sort_index(ascending=False)

NOTA_REDACAO
1000.0       5
980.0     1049
960.0     3326
940.0     5177
920.0     7295
900.0     6757
Name: count, dtype: int64

In [139]:
vestibulando['TP_PRESENCA_CH'].value_counts()

TP_PRESENCA_CH
1    355946
0    164056
2       455
Name: count, dtype: int64

In [140]:
vestibulando['TP_PRESENCA_LC'].value_counts()

TP_PRESENCA_LC
1    355946
0    164056
2       455
Name: count, dtype: int64

In [141]:
vestibulando['TP_PRESENCA_CN'].value_counts()

TP_PRESENCA_CN
1    332397
0    187870
2       190
Name: count, dtype: int64

In [142]:
vestibulando['TP_PRESENCA_MT'].value_counts()

TP_PRESENCA_MT
1    332397
0    187870
2       190
Name: count, dtype: int64

In [144]:
vestibulando['TP_STATUS_REDACAO'].value_counts().sort_index()

TP_STATUS_REDACAO
1.0    346435
2.0       785
3.0       908
4.0      3479
6.0      2832
7.0       486
8.0       560
9.0       461
Name: count, dtype: int64

In [147]:
vestibulando['IDADE'].isnull().sum()

np.int64(0)

In [148]:
provas = [ 'NOTA_REDACAO', 'NOTA_CN', 'NOTA_MT', 'NOTA_LC', 'NOTA_CH']
vestibulando[provas].isnull().sum()

NOTA_REDACAO    164511
NOTA_CN         188060
NOTA_MT         188060
NOTA_LC         164511
NOTA_CH         164511
dtype: int64

In [150]:
vestibulando_classificados = vestibulando.loc[vestibulando.TP_PRESENCA_CH == 1]
vestibulando_classificados = vestibulando.loc[vestibulando.TP_PRESENCA_MT == 1]

In [153]:
vestibulando_classificados['TP_PRESENCA_MT'].value_counts()

TP_PRESENCA_MT
1    332397
Name: count, dtype: int64

In [ ]:
vestibulando_classificados['TP_PRESENCA_CH'].value_counts()

TP_PRESENCA_CN
1    332397
Name: count, dtype: int64

In [156]:
vestibulando_classificados[provas].isnull().sum()

NOTA_REDACAO    620
NOTA_CN           0
NOTA_MT           0
NOTA_LC         620
NOTA_CH         620
dtype: int64

In [158]:
vestibulando_classificados.query('NOTA_REDACAO == 0')['NOTA_REDACAO'].value_counts()

NOTA_REDACAO
0.0    6477
Name: count, dtype: int64

In [160]:
vestibulando_classificados.query('COMP1 == 0')['COMP1'].value_counts()

COMP1
0.0    6484
Name: count, dtype: int64

In [161]:
vestibulando_classificados.query('COMP2 == 0')['COMP2'].value_counts()

COMP2
0.0    6477
Name: count, dtype: int64

In [162]:
vestibulando_classificados.query('COMP3 == 0')['COMP3'].value_counts()

COMP3
0.0    6490
Name: count, dtype: int64

In [163]:
vestibulando_classificados.query('COMP4 == 0')['COMP4'].value_counts()

COMP4
0.0    6487
Name: count, dtype: int64

In [159]:
vestibulando_classificados.query('COMP5 == 0')['COMP5'].value_counts()

COMP5
0.0    50519
Name: count, dtype: int64

In [164]:
vestibulando_classificados.head()

,NU_INSCRICAO,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",22,M,1,parda,1,Santa Izabel do Pará,1,Não respondeu,0,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
3,"1,90E+11",19,M,1,parda,1,São Bernardo do Campo,2,Pública,0,...,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
8,"1,90E+11",23,F,1,branco,1,São Paulo,1,Não respondeu,0,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim
10,"1,90E+11",18,F,1,branco,1,Belém,2,Pública,0,...,612.8,espanhol,1.0,120.0,160.0,120.0,80.0,100.0,580.0,Não
12,"1,90E+11",32,M,1,parda,1,Pratápolis,1,Não respondeu,0,...,584.1,espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim

In [172]:
vestibulando_classificados = vestibulando_classificados.drop(columns=['IN_TREINEIRO'], errors='ignore')

In [173]:
print(vestibulando_classificados.columns.tolist())

['NU_INSCRICAO', 'IDADE', 'SEXO', 'TP_ESTADO_CIVIL', 'RACA', 'TP_NACIONALIDADE', 'NO_MUNICIPIO_NASCIMENTO', 'TP_ST_CONCLUSAO', 'ESCOLA', 'CO_ESCOLA', 'NO_MUNICIPIO_ESC', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'NOTA_CN', 'NOTA_CH', 'NOTA_LC', 'NOTA_MT', 'TP_LINGUA', 'TP_STATUS_REDACAO', 'COMP1', 'COMP2', 'COMP3', 'COMP4', 'COMP5', 'NOTA_REDACAO', 'INTERNET']

In [174]:
vestibulando_classificados.to_csv('enem_tratado.csv', encoding='iso-8859-1',index=False)